name: .NET

on:
    push:
    pull_request:
    workflow_dispatch:
      inputs:
        deploy:
          type: boolean
          description: Create Release
          default: false
          required: true
      version:
        type: choice
        description: Version to increment
        options:
          - major
          - feature
          - bug
          - rc

env:
  ARTIFACT_PATH: /app/publish
  NEXUS_REPO: https://nexus.crookedcactus.net/repository/nuget/

jobs:
  build:
    name: Build and Test Pipeline
    runs-on: self-hosted
    container:
      image: docker.crookedcactus.net/dev-tools/dotnet:1.1.0
      credentials:
               username: ${{ secrets.REGISTRY_USERNAME }}
               password: ${{ secrets.REGISTRY_PASSWORD }}

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3
    - name: Setup Environment
      run: |
        VER=$(cat ./${{ github.event.inputs.image}}/VERSION)
        echo "VERSION=$VER" >> $GITHUB_ENV
        echo ZIP_FILE=crooked-cactus-api-$VER.zip >> $GITHUB_ENV
    - name: Increment Version
      id: env_setup
      uses: christian-draeger/increment-semantic-version@1.0.2
      with:
        current-version: ${{ env.VERSION }}
        version-fragment: ${{ github.event.inputs.version }}
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: |
        dotnet restore "./CrookedCactusApiSdk/CrookedCactusApiSdk.csproj"
    - name: Build
      run: dotnet build /p:PackageVersion=${{VERSION}} --no-restore -c Release "./CrookedCactusApiSdk/CrookedCactusApiSdk.csproj"
    - name: Pack
      if: ${{ github.event.inputs.deploy }}
      run: dotnet pack  -c Release --no-restore --no-build /p:PackageVersion=${{VERSION}} -o ${{ARTIFACT_PATH}}
    - name: Release
      if: ${{ github.event.inputs.deploy }}
      run: dotnet nuget push ${{ARTIFACT_PATH}}/*.nupkg --source ${NEXUS_REPO} --api-key ${{NEXUS_NUGET_KEY}}
